"""Plot the GEMV shape sweep: achieved GB/s vs N for cuBLAS and the Triton kernels.

Reads the tee'd logs produced by gemv_triton.py (no GPU needed):
    table.log               cuBLAS with allow_bf16_reduced_precision_reduction=False
    table-default-flag.log  cuBLAS with the PyTorch default (True)
Triton numbers are taken from table.log (best config per kernel per N).

Run:  python3 plot_sweep.py           # writes gemv_sweep.png next to the logs

This plot was generated by Claude.
"""
import re
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HERE = Path(__file__).parent
PEAK = 936.0  # RTX 3090 DRAM peak, GB/s


def parse(path):
    """Return {N: {"cublas": gbps, "flat": best, "strip": best, "tile2d": best}}."""
    out, N, section = {}, None, None
    for line in path.read_text().splitlines():
        if line.startswith("——— cuBLAS"):
            section = "cublas"; continue
        if line.startswith("——— Triton1d"):
            section = "flat"; continue
        if "NAIVE" in line:
            section = "strip"; continue
        if "TRUE" in line:
            section = "tile2d"; continue
        nums = line.split()
        if section == "cublas" and len(nums) >= 5 and nums[-1] == "GT":
            N = int(nums[0]); out[N] = {"cublas": float(nums[3])}
        elif section in ("flat", "strip", "tile2d") and N is not None:
            m = re.match(r"\s*(\d+)\s+(\d+\s+)?([\d.]+)\s+([\d.]+)\s+[01]\s*$", line)
            if m:
                gbps = float(m.group(4))
                out[N][section] = max(out[N].get(section, 0.0), gbps)
    return out


def main():
    final = parse(HERE / "table.log")
    default = parse(HERE / "table-default-flag.log")
    Ns = sorted(final)

    fig, ax = plt.subplots(figsize=(7.5, 4.6), dpi=150)
    ax.axhline(PEAK, color="#888", ls="--", lw=1)
    ax.text(Ns[0], PEAK + 8, f"DRAM peak {PEAK:.0f} GB/s", color="#666", fontsize=8)

    series = [
        ("flat",   final,   "Triton, one row per program", "#1f77b4", "o"),
        ("tile2d", final,   "Triton, 2D tile",             "#2ca02c", "s"),
        ("cublas", default, "cuBLAS bf16 (PyTorch default)", "#d62728", "^"),
        ("cublas", final,   "cuBLAS bf16 (reduced-precision reduction off)", "#ff9896", "v"),
    ]
    dy = {"flat": 5, "tile2d": -11}
    for key, src, label, color, marker in series:
        ys = [src[n][key] for n in Ns]
        ax.plot(Ns, ys, marker=marker, color=color, label=label, lw=1.6, ms=5)
        ax.annotate(f"{ys[-1]:.0f}", (Ns[-1], ys[-1]), xytext=(6, dy.get(key, -3)),
                    textcoords="offset points", fontsize=8, color=color)

    ax.set_xscale("log", base=2)
    ax.set_xticks(Ns); ax.set_xticklabels([f"{n}²" for n in Ns])
    ax.set_xlabel("matrix size N = K (bf16, W is N×N)")
    ax.set_ylabel("achieved GB/s")
    ax.set_ylim(400, 1000)
    ax.set_title("GEMV y = W·x on RTX 3090: achieved bandwidth vs size")
    ax.grid(alpha=0.25)
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    out = HERE / "gemv_sweep.png"
    fig.savefig(out)
    print("wrote", out)
    for n in Ns:
        print(f"{n:>6}  cuBLAS default {default[n]['cublas']:6.1f}  flag-off {final[n]['cublas']:6.1f}"
              f"  flat {final[n]['flat']:6.1f}  strip {final[n]['strip']:6.1f}  2D {final[n]['tile2d']:6.1f}")


if __name__ == "__main__":
    main()
